Repository Gam-develop/GAM-iOS, pull requests merged in 2024-05, with the labels that each got.

#123 [FIX] 차단 API 연결 및 본인 프로필 스크랩/신고,차단 제외
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Global/Bases/BaseViewController.swift
  GAM/GAM/Network/DTO/User/Request/BlockUserRequestDTO.swift
  GAM/GAM/Network/Routers/UserRouter.swift
  GAM/GAM/Network/Services/UserService.swift
  GAM/GAM/Sources/Components/CollectionViewCell/BrowseDiscoverCollectionViewCell.swift
  GAM/GAM/Sources/Components/View/GamNavigationView.swift
  GAM/GAM/Sources/Screens/User/UserViewController.swift
Labels: bug, feature, qa

#127 [FIX] 마이페이지 이미지 필요없는 여백 삭제
  GAM/GAM/Global/Extensions/UIImageView+.swift
  GAM/GAM/Sources/Components/TableViewCell/PortfolioTableViewCell.swift
  GAM/GAM/Sources/Screens/User/WriteProjectViewController.swift
Labels: chore, qa

#129 [CHORE] 마이페이지 탭 페이징 하단 간격 롤백
  GAM/GAM/Sources/Screens/User/MyViewController.swift
  GAM/GAM/Sources/Screens/User/UserViewController.swift
Labels: chore, qa

#131 [CHORE] 마이페이지 infoview 좌측 간격 수정
  GAM/GAM/Sources/Components/View/ProfileInfoView.swift
Labels: bug, chore, qa

#132 [FEAT] 신고 API 연결
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Global/Bases/BaseViewController.swift
  GAM/GAM/Global/Extensions/UIViewController+.swift
  GAM/GAM/Network/DTO/User/Request/ReportUserRequestDTO.swift
  GAM/GAM/Network/Routers/UserRouter.swift
  GAM/GAM/Network/Services/UserService.swift
Labels: feature

#134 [CHORE] NetworkLogger 편의성 수정
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Global/Extensions/Data+.swift
  GAM/GAM/Network/NetworkLoggerPlugin.swift
Labels: chore

#135 [CHORE] debugPrint for GAM.. util 함수 만들기
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Applications/AppDelegate.swift
  GAM/GAM/Global/Extensions/UIViewController+.swift
  GAM/GAM/Global/Utils/gamPrint.swift
  GAM/GAM/Network/Services/AuthService.swift
  GAM/GAM/Network/Services/MagazineService.swift
  GAM/GAM/Network/Services/PublicService.swift
  GAM/GAM/Network/Services/UserService.swift
  GAM/GAM/Sources/Screens/Magazine/MagazineDetailViewController.swift
  GAM/GAM/Sources/Screens/Setting/SecessionViewModel.swift
  GAM/GAM/Sources/Screens/SignIn/SignInViewController.swift
  GAM/GAM/Sources/Screens/SignIn/SplashViewController.swift
Labels: chore

#133 [FEAT] 앱 사용 중 엑세스토큰 리프레시 처리(interceptor)
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Network/APIEssentials/GamMoyaProvider.swift
  GAM/GAM/Network/AuthIntercepter.swift
  GAM/GAM/Network/Routers/MagazineRouter.swift
  GAM/GAM/Network/Routers/PublicRouter.swift
  GAM/GAM/Network/Routers/UserRouter.swift
Labels: chore

#137 Chore/#36 매거진 토큰 처리
  GAM/GAM/Network/AuthIntercepter.swift
  GAM/GAM/Sources/Screens/Magazine/MagazineDetailViewController.swift
Labels: chore, qa

#138 [CHORE] 둘러보기 검색 조회수 없애기
  GAM/GAM/Sources/Components/TableViewCell/NoScrapMagazineTableViewCell.swift
Labels: chore, qa

#142 [CHORE] 매거진 공유 버튼 hidden
  GAM/GAM/Sources/Screens/Magazine/MagazineDetailViewController.swift
Labels: chore, qa

#146 [FEAT] 닉네임 수정
  GAM/GAM/Network/DTO/User/Request/UpdateMyProfileRequestDTO.swift
  GAM/GAM/Network/DTO/User/Response/UpdateProfileResponseDTO.swift
  GAM/GAM/Sources/Entities/UserProfileEntity.swift
  GAM/GAM/Sources/Screens/User/EditProfileViewController.swift
  GAM/GAM/Sources/Screens/User/MyViewController.swift
Labels: feature

#149 [CHORE] 앱 아이콘 변경
  GAM/GAM/Global/Extensions/UIImage+.swift
  GAM/GAM/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/AppIcon.appiconset/gam_appIcon.png
  GAM/GAM/Resources/Assets.xcassets/AppIcon.appiconset/logo_gam.png
  GAM/GAM/Resources/Assets.xcassets/OnBoarding/gamLogoKorean.imageset/gamLogoKorean.svg
  GAM/GAM/Resources/Assets.xcassets/OnBoarding/logo_gam.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/OnBoarding/logo_gam.imageset/logo_gam 1.png
  GAM/GAM/Resources/Assets.xcassets/OnBoarding/logo_gam.imageset/logo_gam 2.png
  GAM/GAM/Resources/Assets.xcassets/OnBoarding/logo_gam.imageset/logo_gam.png
  GAM/GAM/Sources/Base.lproj/LaunchScreen.storyboard
  GAM/GAM/Sources/Screens/SignIn/SignInViewController.swift
  GAM/GAM/Sources/Screens/SignIn/SplashViewController.swift
Labels: chore
