Repository Gam-develop/GAM-iOS, pull requests merged in 2024-03, with the labels that each got.

#104 [CHORE] 검색 textField placeholder 수정
  GAM/GAM/Sources/Components/TextField/GamSearchTextField.swift
  GAM/GAM/Sources/Screens/Search/SearchViewController.swift
Labels: chore

#106 [FIX] 스크랩 시 토스트메시지 구현
  GAM/GAM/Global/Bases/BaseViewController.swift
  GAM/GAM/Global/Enums/ToastMessageType.swift
Labels: qa

#107 Chore/#102 qa( 로직) 반영
  GAM/GAM/Sources/Screens/User/AddContactURLViewController.swift
  GAM/GAM/Sources/Screens/User/WriteProjectViewController.swift
Labels: qa

#111 [FIX] 온보딩 닉네임 글자수 변경
  GAM/GAM/Sources/Screens/SignUp/SignUpUsernameViewController.swift
Labels: qa

#114 [CHORE] 필터 영역 탭 가능하도록 수정
  GAM/GAM/Sources/Components/View/SelectedFilterTagView.swift
  GAM/GAM/Sources/Screens/Browse/BrowseDiscoverViewController.swift
  GAM/GAM/Sources/Screens/Browse/BrowseViewController.swift
Labels: bug, qa

#117 [CHORE] 행간 수정
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Global/Extensions/UILabel+.swift
  GAM/GAM/Global/Extensions/UITextView+.swift
  GAM/GAM/Sources/Components/TableViewCell/PortfolioTableViewCell.swift
  GAM/GAM/Sources/Components/View/ProfileInfoView.swift
  GAM/GAM/Sources/Screens/Setting/SecessionViewController.swift
  GAM/GAM/Sources/Screens/User/EditProfileViewController.swift
  GAM/GAM/Sources/Screens/User/MyProfileViewController.swift
  GAM/GAM/Sources/Screens/User/UserProfileViewController.swift
  GAM/GAM/Sources/Screens/User/WriteProjectViewController.swift
Labels: qa

#119 [CHORE] QA 반영 1차
  GAM/GAM/Global/Bases/BaseViewController.swift
  GAM/GAM/Resources/Assets.xcassets/Global/icnCircleMore.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnFilterBlack.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnFilterBlack.imageset/type=filter.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnFilterGray.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnFilterGray.imageset/type=filter_inactive.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnModalX.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnMoreDefault.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnMoreDefault.imageset/icnMoreDefault.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnMoreDefault.imageset/type=kebab.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnSearch.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnSearch.imageset/icnSearch.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnSearch.imageset/type=search.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnSetting.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnSetting.imageset/icnSetting.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnSetting.imageset/type=setting.svg
  GAM/GAM/Resources/Assets.xcassets/Global/icnShare.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/icnSmallX.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/textFieldClear.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/textFieldClear.imageset/type=delete.svg
  GAM/GAM/Resources/Assets.xcassets/Global/typeChevronLeft.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/Global/typeChevronLeft.imageset/type=chevron_left.svg
  GAM/GAM/Resources/Assets.xcassets/Global/typeChevronLeft.imageset/typeChevronLeft.svg
  GAM/GAM/Resources/Assets.xcassets/Global/visibilityGray.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIcon.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIcon.imageset/Property 1=discover, active=off.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIcon.imageset/property1DiscoverActiveOff.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIconSelected.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIconSelected.imageset/Property 1=discover, active=on.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/browseTabIconSelected.imageset/property1DiscoverActiveOn.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIcon.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIcon.imageset/Property 1=home, active=off.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIcon.imageset/property1HomeActiveOff.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIconSelected.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIconSelected.imageset/Property 1=home, active=on.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/homeTabIconSelected.imageset/property1HomeActiveOn.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIcon.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIcon.imageset/Property 1=magazine, active=off.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIcon.imageset/property1MagazineActiveOff.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIconSelected.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIconSelected.imageset/Property 1=magazine, active=on.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/magazineTabIconSelected.imageset/property1MagazineActiveOn.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIcon.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIcon.imageset/Property 1=my, active=off.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIcon.imageset/property1MyActiveOff.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIconSelected.imageset/Contents.json
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIconSelected.imageset/Property 1=my, active=on.svg
  GAM/GAM/Resources/Assets.xcassets/TabBar/mypageTabIconSelected.imageset/property1MyActiveOn.svg
  GAM/GAM/Sources/Components/CollectionViewCell/BrowseDiscoverCollectionViewCell.swift
  GAM/GAM/Sources/Screens/SignUp/SignUpInfoViewController.swift
Labels: bug, qa

#118 [CHORE] 디자인 수정 qa2
  GAM/GAM.xcodeproj/project.pbxproj
  GAM/GAM/Global/Extensions/Int+.swift
  GAM/GAM/Sources/Components/TableViewCell/MagazineTableViewCell.swift
  GAM/GAM/Sources/Components/View/GamNavigationView.swift
  GAM/GAM/Sources/Screens/Home/HomeViewController.swift
Labels: qa
